### ISSUE TITLE
HGMD annotations

### ISSUE THREAD

**Issue by jchap14** [sigven/gvanno#12]
Hi,

Is there currently a way to pull in HGMD annotations? I see that gvanno does rely on VEP, which is capable of doing this.

Thanks,
James

**Comment by sigven** [comment]
Hi James,

Thanks for reaching out. I am sure this can be obtained, but you should be aware of the following: Due to the licensed nature of HGMD, VEP does not provide an _allele-specific match_ against HGMD variant, only indicating at [which positions HGMD variants are found](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#colocated). But that might be valuable also, I guess. I tend to think ClinVar currently provides the most abundant data in this regard (disease-associated variants), but historically HGMD has indeed been widely used. Let me provide this info in a dedicated column in the next release. Thanks for the input!

**Comment by jchap14** [comment]
I totally forgot about the licensing issue. I would be curious to see what public data is able to be pulled and will be on the lookout for any updates.

Thanks,
James

**Comment by sigven** [comment]
Just tried the public VEP tool with some small variant datasets for testing. So, what you'll get in terms of HGMD annotation is essentially a variant identifer (i.e. `CMXXXXX`). As mentioned above, these are matched to the genomic position, _not_ allele-specific towards a given query variant. No phenotype information etc. is provided by for these identifiers, as I guess it violates the nature of the licensing.

**Comment by jchap14** [comment]
Ahh OK, sounds like I would need to get the licensed dataset and try to annotate with it separately.

Thanks for trying it
