### ISSUE TITLE
Why "single sample"?

### ISSUE THREAD

**Issue by carbocation** [sigven/gvanno#2]
From the README:
```md
The gvanno workflow accepts a single input file:

An unannotated, single-sample VCF file
```
Is single-sample specified because this is more efficient than consuming a large multi-sample file? Or is there any additional reason?

**Comment by sigven** [comment]
Hi,

Very good point! To answer your question: Processing each sample at a time will be more time-consuming and far less efficient than processing a multi-sample VCF. However, over the years, I have seen a huge number of messy VCF files, in which adherence to the formatting standards is the exception rather than the norm. And my experience is that multi-sample VCF files appears even more likely as messy than single-sample VCF files. This is complicated further by the presence of multi-allelic entries in the VCF, which is a bit of a nightmare for annotation purposes. 

I have thus chosen, to keep it simple, to support single-sample VCF's at this point. But if you have a multi-sample VCF you want to try out, I'd by happy to help you out, and see if we could make it work. The last part of the workflow (vcf2tsv) should support such multisample VCF files (i.e. result file will give you one line pr sample-variant entry).

best,
Sigve

**Comment by carbocation** [comment]
Thanks! That's helpful. So if I understand correctly, if I use this with a VCF that has multiallelics, the vcf2tsv step should work, but the multiallelic sites might not get annotated correctly beforehand in the pipeline?

I'm basically looking for a general purpose VCF annotator which doesn't require me to maintain my own docker with VEP + dbNSFP. But, I will end up having many multi-allelic sites, so that's something I'm watching out for.

**Comment by carbocation** [comment]
For now, I'm just removing all genotypes except for one (`cut -f 1-9`). So far, this seems to be running fine.

**Comment by sigven** [comment]
Sounds like a reasonable strategy, this is in fact similar to what I have done previously (to make the VCF content as simple as possible)

**Comment by carbocation** [comment]
Sounds great. Going to close this issue since it sounds more like an efficiency thing rather than a correctness thing.
